// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpb6aee7M3JHcnzUB3h9RGjnCsAU4cX1o',
    appId: '1:269585609130:web:6a31df0d83601074d9bbd3',
    messagingSenderId: '269585609130',
    projectId: 'cmsc23-project-villavicencio',
    authDomain: 'cmsc23-project-villavicencio.firebaseapp.com',
    storageBucket: 'cmsc23-project-villavicencio.appspot.com',
    measurementId: 'G-NXRSD7PB9Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0KEsaaUFJMVYvMz2qKxy3zmfF6f0VorY',
    appId: '1:269585609130:android:0ab56009ab16e78ed9bbd3',
    messagingSenderId: '269585609130',
    projectId: 'cmsc23-project-villavicencio',
    storageBucket: 'cmsc23-project-villavicencio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLUVXyvTdPf3VQQlFAZPhJ1--6CrO94s',
    appId: '1:269585609130:ios:37a75c223f767c96d9bbd3',
    messagingSenderId: '269585609130',
    projectId: 'cmsc23-project-villavicencio',
    storageBucket: 'cmsc23-project-villavicencio.appspot.com',
    iosClientId: '269585609130-6svqb595amfe4g23d1326bdkq9kfu21j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23ProjectVillavicencio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxLUVXyvTdPf3VQQlFAZPhJ1--6CrO94s',
    appId: '1:269585609130:ios:37a75c223f767c96d9bbd3',
    messagingSenderId: '269585609130',
    projectId: 'cmsc23-project-villavicencio',
    storageBucket: 'cmsc23-project-villavicencio.appspot.com',
    iosClientId: '269585609130-6svqb595amfe4g23d1326bdkq9kfu21j.apps.googleusercontent.com',
    iosBundleId: 'com.example.cmsc23ProjectVillavicencio',
  );
}
